### ISSUE TITLE
UI: Input files with a .yml extension cause misleading exception

### ISSUE THREAD

**Issue by os6sense** [s-ga/kwalify_to_json_schema#17]
Firstly, thank you greatly for this tool! It's going to save me a huge amount of time and I had expected to have to come up with a solution myself so finding this and it working has been a highpoint to my week. 

A minor bug is if called against a valid kwalify schema with a .yml extension, an exception is raised. It's also somewhat misleading in that once the file is renamed things work as expected (better than expected actually since it looks like kwalify ignores aliases where as json schema and ajv doesn't!).

```
➜  config_schemas git:(aj/CS-1083) ✗ kwalify_to_json_schema convert export_profiles.schema.yml export_profiles.schema.json                                                                     
Traceback (most recent call last):                                                                                                                                                             
        12: from /home/leej/.rbenv/versions/2.7.5/bin/kwalify_to_json_schema:23:in `<main>'    
        11: from /home/leej/.rbenv/versions/2.7.5/bin/kwalify_to_json_schema:23:in `load'      
        10: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/kwalify_to_json_schema-0.6.0/bin/kwalify_to_json_schema:4:in `<top (required)>'                                     
         9: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'                                                                          
         8: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'                                                                            
         7: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'                                                           
         6: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'                                                                          
         5: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/kwalify_to_json_schema-0.6.0/lib/kwalify_to_json_schema/cli.rb:46:in `convert'                                      
         4: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/kwalify_to_json_schema-0.6.0/lib/kwalify_to_json_schema/kwalify_to_json_schema.rb:28:in `convert_file'              
         3: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/kwalify_to_json_schema-0.6.0/lib/kwalify_to_json_schema/serialization.rb:6:in `deserialize_from_file'               
         2: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/kwalify_to_json_schema-0.6.0/lib/kwalify_to_json_schema/serialization.rb:37:in `deserialize'                        
         1: from /home/leej/.rbenv/versions/2.7.5/lib/ruby/2.7.0/json/common.rb:156:in `parse' 
/home/leej/.rbenv/versions/2.7.5/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '--- (JSON::ParserError)                    
```

Happy to submit a patch assuming this is maintained?

**Comment by s-ga** [comment]
Hi,
Thanks for reporting.
Release 0.6.1 add missing support for `.yml` extension
